### ISSUE TITLE
Scripts com Túnel SSH para servidores privados.

### ISSUE THREAD

**Issue by rzrlew** [Morierti/GRS#21]
Os servidores privados não vão ser acessíveis remotamente. Assim o administrator deverá criar um túnel SSH com um Servidor público que reencaminha para o servidor privado que é pretendido aceder.
È necessário criar uma máquina para o administrador ligada ao routerISP.

**Comment by rzrlew** [comment]
Adicionei a máquina adminPC com ip 10.0.0.9/30 ligada á interface eth2 do routerISP com ip 10.0.0.10/30.

**Comment by Morierti** [comment]
Verifica que puses-te o ficheiros sff, que eu no meu não tenho nada o adminPC

**Comment by Morierti** [comment]
Fechei, estas já estão a funcionar e a ligação já é feixa usando chaves públicas.
